spring:
  application:
    name: Coding Challenge
  profiles:
    include: populate
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    name: evcc
    hikari:
      poolName: Hikari
      auto-commit: false
    # shared file database:
    # url: jdbc:h2:file:~/.evcc;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9999
    # in-memory database
    url: jdbc:h2:mem:evcc;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  info:
    git:
      mode: full

server:
  port: 8081
